[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "python manage.py collectstatic --noinput",
    "python manage.py migrate",
    "python manage.py sync_content"  # 添加内容同步命令
]

[deploy]
startCommand = "gunicorn config.wsgi:application"
healthcheckPath = "/"