[build]
builder = "NIXPACKS"
buildCommand = "npm ci"
nixpacksPlan = {"phases":{"setup":{"nixPkgs":["...","nodejs"]}},"providers":["python"]}

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "python manage.py migrate && python manage.py sync_content && python manage.py collectstatic --noinput && gunicorn config.wsgi"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10