[build]
builder = "NIXPACKS"
buildCommand = """
pip install -r requirements.txt && \
python manage.py collectstatic --noinput
"""

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = """python manage.py migrate && python manage.py sync_content && gunicorn config.wsgi:application"""
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10