[build]
builder = "NIXPACKS"
buildCommand = """
pip install --upgrade pip && \
pip install -r requirements.txt && \
python manage.py collectstatic --noinput && \
python manage.py migrate && \
python manage.py sync_content
"""

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "gunicorn config.wsgi:application"
healthcheckPath = "/"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10